name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bogdan/setup-racket@v1
        with:
          version: stable
          distribution: full
          architecture: x64
      - name: Install package
        run: raco pkg install --auto --batch --name recspecs .
      - name: Build package
        run: raco setup --check-pkg-deps --unused-pkg-deps recspecs
      - name: Run tests
        run: raco test -x -p recspecs
