name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Bogdanp/setup-racket@v1.13
        with:
          version: stable
          distribution: full
          architecture: x64
      - name: Install packages
        run: raco pkg install --auto ./recspecs-lib ./recspecs
      - name: Build package
        run: raco setup --check-pkg-deps --unused-pkg-deps recspecs
      - name: Run tests
        run: raco test -p recspecs
